### ISSUE TITLE
"Silverlight" thus not for 

### ISSUE THREAD

**Issue by sanderjo** [andrewreed/Fingerprinter#1]
Question:

http://www.mjkranch.com/docs/CODASPY17_Kranch_Reed_IdentifyingHTTPSNetflix.pdf says

> For browser-based streaming, Netflix first encodes their videos as variable bitrate (VBR) MPEG4 and then streams them using Dynamic Adaptive Streaming over HTTP (DASH) via **Microsoft Silverlight**

Does this mean that the fingerprinting / identifying doesn't work with browser-based streaming on Linux, where no Microsoft Silverlight is involved (at least: on the client-side)?

**Comment by andrewreed** [comment]
The underlying issue is not with Microsoft Silverlight, but instead with the combination of VBR (for video encoding) and DASH (for delivery/streaming). I will check later today to see what Netflix is currently using for Firefox/Chrome on Linux, but when I checked about a year ago this time, Netflix was using DASH to stream to Chrome (I think with their HTML5 player).

Bottom Line: Any video service that uses VBR with DASH is at risk of traffic identification using our technique (or something similar) ... it just so happens that Netflix really seems to have "cranked up the knobs" on their VBR encoder to the point where their videos are highly distinguishable.

**Comment by sanderjo** [comment]
OK, thank you for clarifying! 

Very interesting research.
